// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTL5hY1wm3vJUKC9EGXLOYV3ehBtYYHPA',
    appId: '1:972871195029:web:55071186c83c9a2374fe9c',
    messagingSenderId: '972871195029',
    projectId: 'api-mushbox',
    authDomain: 'api-mushbox.firebaseapp.com',
    storageBucket: 'api-mushbox.firebasestorage.app',
    measurementId: 'G-HBGF15TR55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXXod1LzkL3muZWLNlehszE4W2Vm6Jek',
    appId: '1:972871195029:android:f0ebf47a5c072df974fe9c',
    messagingSenderId: '972871195029',
    projectId: 'api-mushbox',
    storageBucket: 'api-mushbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFw3NkhvazxL1mj5nbrmQGWNyNsou52XQ',
    appId: '1:972871195029:ios:b9d790d1d946066b74fe9c',
    messagingSenderId: '972871195029',
    projectId: 'api-mushbox',
    storageBucket: 'api-mushbox.firebasestorage.app',
    iosBundleId: 'com.example.mushboxApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFw3NkhvazxL1mj5nbrmQGWNyNsou52XQ',
    appId: '1:972871195029:ios:b9d790d1d946066b74fe9c',
    messagingSenderId: '972871195029',
    projectId: 'api-mushbox',
    storageBucket: 'api-mushbox.firebasestorage.app',
    iosBundleId: 'com.example.mushboxApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTL5hY1wm3vJUKC9EGXLOYV3ehBtYYHPA',
    appId: '1:972871195029:web:45d90990cba4259c74fe9c',
    messagingSenderId: '972871195029',
    projectId: 'api-mushbox',
    authDomain: 'api-mushbox.firebaseapp.com',
    storageBucket: 'api-mushbox.firebasestorage.app',
    measurementId: 'G-9T7F63JJB2',
  );
}
